name: C/C++ CI

on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master,devel ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt-get install gsl-bin libgsl0-dev
    - name: make
      run: cd Model && make -B 
